### ISSUE TITLE
"structure" appearing in manifest

### ISSUE THREAD

**Issue by stuzart** [myGrid/ruby-ro-bundle#1]
When added a created_by to the ro bundle file, the agent JSON appears in the manifest with "structure" as a key.

e.g:

``` ruby
ro = ROBundle::File.create(filename)
creator = ROBundle::Agent.new("Stuart Owen","https://seek.sysmo-db.org/people/134","http://orcid.org/111-111")
ro.created_by=creator
ro.commit
```

results in the manifest JSON looking like:

``` json
{"@context":["https://w3id.org/bundle/context"],"id":"/","createdBy":{"structure":{"name":"Stuart Owen","uri":"https://seek.sysmo-db.org/people/134","orcid":"http://orcid.org/111-111"}}}
```

**Comment by hainesr** [comment]
I haven't managed to replicate this yet. I've added a test to the next branch that checks manifest JSON output and that is passing with different rubies and json version 1.8.2:

https://travis-ci.org/myGrid/ruby-ro-bundle/builds/51624822

**Comment by stuzart** [comment]
It seems to be something specific to my rails environment. Maybe some gem is overriding the JSON generation behaviour - although I am using the same versions of the json gems.
I'll be doing some more investigating today and will let you know.

**Comment by stuzart** [comment]
I have an idea now what is going on. But no idea yet why or how to fix it !
It seems that within my app, when calling the to_json on the Manifest, this isn't passing on to the agent as expected. Outside of the app it calls to_json on the Agent. However, called from within my rails app it doesn't and just creates JSON for the class level hashes.
e.g. if I add
@fish = {:fred=>"monkey"}

to the end of the Agent initialize, the resulting json contains:
,\"fish\":{\"fred\":\"monkey\"}}

I've also added a raise within the Agent#to_json, which isn't being thrown

**Comment by stuzart** [comment]
OK, it's caused by a conflict with the rails json helper. I am now applying a fix.
